### ISSUE TITLE
When using `wac` as a library, it interacts

### ISSUE THREAD

**Issue by itowlson** [bytecodealliance/wac#139]
I am using `wac` (specifically, the `wac_resolver` crate) as a library in another program.  As part of this, I call `RegistryPackageResolver::resolve()`.  I am using the `wa.dev` registry for dev-test purposes, and when I try to resolve a package for the first time I get this:

```
? Package `fermyon:spin` is not in `warg.wa.dev` registry.
Registry recommends using `fermyon.wa.dev` registry for packages in `fermyon` namespace.
Accept recommendation y/N
```

These prompts come from `warg_client`, and I'd like to be able to opt out of them, e.g. in CI scenarios.

It seems like `warg_client` has a `cli-interactive` feature, which is on by default.  Would it be possible for `wac` to surface a similar feature?  (I'm happy to send a PR for this if you're open to it.)

**Comment by itowlson** [comment]
Hmm, although it looks like Warg's behaviour if _not_ allowed to interact might be to fail so whee.

**Comment by itowlson** [comment]
Thanks @calvinrp.  I don't really want to rely on users installing and configuring `warg` - but if `wkg` is going to solve this then that's cool, I probably need to wait for `wac` to adopt `wkg` before I can ship my feature anyway!  Closing!

**Comment by calvinrp** [comment]
We are getting closer on `wkg` updates. But I wanted to understand the change here that will help.

To confirm, you'd like `wac` configurable so that it doesn't ask for user input while running in a CI/CD process?

**Comment by itowlson** [comment]
@calvinrp My specific context is that I am using `wac_resolver` as a _library_ and I want _my_ program to (have the option to) not interact.  So yes to being able to configure the `wac` _crates_, and no opinion on the `wac` CLI tool.  Hopefully that clarifies - I'm happy to go into more detail if that would be useful.  Thanks!

**Comment by calvinrp** [comment]
@itowlson release 0.6.0 should fix, can you confirm?

**Comment by itowlson** [comment]
That seems to be working fine.  Thank you @calvinrp!
