### ISSUE TITLE
Can we build release binaries with static libc?

### ISSUE THREAD

**Issue by ouillie** [bytecodealliance/wac#142]
The [pre-built binary](https://github.com/bytecodealliance/wac/blob/main/.github/workflows/publish-binaries.yml) targets use dynamic glibc (e.g. `x86_64-unknown-linux-gnu`), but they could also be compiled with statically-linked musl libc (e.g. `x86_64-unknown-linux-musl`). I just tried doing this locally for v0.6.0 and it worked without modifying any source code. Furthermore, I was surprised to learn that the musl version is actually slightly smaller than the glibc version (21MB vs 22MB) despite having nothing in the dynamic symbol table (verified with `objdump -T`).

Would anybody be opposed to switching over to statically-linked pre-built binaries like this? This ought to strictly improve compatibility, which is pretty important for pre-built binaries. I was running into issues trying to use the pre-built binaries in [Bazel's CI pipeline](https://buildkite.com/bazel/bcr-presubmit/builds/8232#01929ec5-51bd-4eb8-b2b4-f5acb7782347).

**Comment by calvinrp** [comment]
No objections. Want to submit a PR?

**Comment by calvinrp** [comment]
Released as `0.6.1`, which I think was safe as a patch version.

https://github.com/bytecodealliance/wac/releases/tag/v0.6.1
