### ISSUE TITLE
Integrate this repository with `wasm-tools`

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wac#35]
This issue outlines my plan for integrating this repository with `wasm-tools`:

* Move (with history) the `wac-parser` and `wac-resolver` crates into `wasm-tools`.
* Begin publishing the new crates to crates.io.
* Remove the `wac` standalone binary in favor of extending `wasm-tools compose` to provide the same functionality.
* Implement additional support in `wasm-compose` for composing via wac documents.
* Add a deprecation warning for the `--config` option of `wasm-tools compose` with the anticipation that support for the yaml syntax will eventually be removed.

**Comment by fibonacci1729** [comment]
We discussed last WAC meeting but It seems like there is a strong possibility that `wasm-compose` will need to take a dependency on `wasmtime` in the not too distant future to implement features like component transformation which will create a depenency cycle between `wasm-tools` and `wasmtime`. Is it still the plan to move in to `wasm-tools` or have `wasm-compose` be standalone repo? Or will it be fine to re-evaluate once we actually have those features in a ship-able state?

**Comment by peterhuene** [comment]
Yeah, I forgot where exactly we left things with the dependency on `wasmtime` forth-coming.

Perhaps we should simply transfer this to a BCA repo and leave the standalone `wac` binary and continue development until such a time that putting it in wasm-tools seems worth it.

**Comment by peterhuene** [comment]
Closing this as this is now a separate BA repo.
